### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Petros-** [bomberstudios/artboard-manager#1]
Ale, I'm really psyched to try this out, but I can't figure out how. I Googled around some but I still can't figure out what to do after I downloaded the repo. Do you have a quick set of steps I should follow? Thanks a ton for developing this!

**Comment by gyanl** [comment]
Could you please add the .sketchplugin file to the repository? Most plugins have it, so I was also quite confused when I cloned the repo and it wasn't there.

**Comment by Petros-** [comment]
I think it got added, because when I downloaded again I was able to install it by opening the Sketch file. I'm working on a file with artboards that are 1280x810 and it is rearranging their order in the layer list when I move them on the canvas. Pretty cool!
