### ISSUE TITLE
Wrong vertical distance

### ISSUE THREAD

**Issue by ivancucer** [bomberstudios/artboard-manager#14]
Hello @bomberstudios 

I have no idea but I'm getting the wrong vertical distance `250px` 🤷‍♂️

<img width="2560" alt="screenshot" src="https://user-images.githubusercontent.com/2349195/29663620-4b447e54-88cc-11e7-9c68-6c6fabb51439.png">

Bug? 🐛 

Best!
Ivan

**Comment by bomberstudios** [comment]
The vertical distance does not really work as one can imagine initially (and maybe it's not the best name, tbh, so I'll have to change it as some point…). Basically, I split the canvas in rows of `gridVerticalSpace` pixels high, and then use those to snap artboards, so the actual distance between two artboards depends on the height of the artboard.

Hope that makes it clearer…
