### ISSUE TITLE
Doesn't work with artboards that are converted into symbols

### ISSUE THREAD

**Issue by iansoper** [bomberstudios/artboard-manager#17]
I appears the plugin doesn't support artboards when they are a also symbols. When an artboard is converted into a symbol it doesn't automatically rearrange them when they are moved.

**Comment by bomberstudios** [comment]
This will be fixed in v1.6.0! It is currently in beta, but I hope to merge the changes (in the `sketch-api` branch) soon

**Comment by jonstoked** [comment]
I would so love to see this as well.
