### ISSUE TITLE
Automatic pixel snapping doesn't seem to work

### ISSUE THREAD

**Issue by webdesserts** [bomberstudios/artboard-manager#2]
Not sure if I'm interpreting this right but it sounded like the artboards were supposed to automatically snap on move/resize, but right now I have to manually use the keyboard shortcut. Am I missing anything?

![jul-24-2017 15-25-53](https://user-images.githubusercontent.com/916253/28543173-8b971378-7084-11e7-9838-180da525d8c1.gif)

**Comment by webdesserts** [comment]
Ahh I figured out the issue, All of my artboards are symbols. Seems to only work with pure artboards atm.

**Comment by bomberstudios** [comment]
Yes, Symbols are an entirely different beast and I don’t think this approach works well with them. If I ever come up with something good for Symbols, I’ll update the README

**Comment by webdesserts** [comment]
@bomberstudios understandable. A note though. It seems a bit odd that the automatic pixel snapping doesn't work with symbols, while the "Arrange Artboards" keyboard shortcut **does**. I would expect the plugin to either fully support symbols or not support them at all.
