### ISSUE TITLE
Conflict with Paddy 2 (BETA)

### ISSUE THREAD

**Issue by nickm717** [bomberstudios/artboard-manager#21]
I am pretty confident there is a conflict with Paddy 2 and this plugin. I started using this this morning and ran into Sketch crashing bugs with all the newest artboards I created since I started using this plugin. If I deactivate Paddy, then the file opens fine. If I delete all the work from this morning and reactivate Paddy, it also works fine. 

Not sure the cause of this or what's going on in the background, but just wanted to bring it to light. Will post the same on [Paddy 2.](https://github.com/DWilliames/paddy2-beta)

**Comment by bomberstudios** [comment]
Thanks for the report, will take a look as soon as I have some spare cycles 👍
