### ISSUE TITLE
Reconfiguring Artboard Positions

### ISSUE THREAD

**Issue by justinjiangrws** [bomberstudios/artboard-manager#23]
Hello,

First off - just wanted to say what a convenient plugin this is!

Think this issue would best understood along with a graphical explanation.

Take this page configuration:

----------

[a] [b] [c]
[d] [e] [f]

----------

I think I'm currently experiencing issues with the automatic positioning of the artboards. It seems like I can arrange my entire page of artboards such that all artboards are aligned with the top-left most artboard [a]. So if I move [a] left (in the -x direction of a 2D plane), [b] would follow suit, [c] would as well, [d] etc.... This behavior works moving [a] up and down (+/- y directions). However if I try to move artboard [a] to the right, it will just snap back to where it was. Naturally, the artboards on the page are all gradually shifting to the left without an ability to reconfigure them to the origin (0,0).

At the end of the day, this is just a small detail but I guess just enough of a problem for me to write this up haha. It'd be cool if I were able to designate an 'anchor' artboard, that moves all the other artboards in the page relative to their position to the 'anchor'.

Thanks and keep up the good work!

**Comment by bomberstudios** [comment]
Hi there. I've updated the code for the plugin with a new algorithm that (I think) works way better than the old one. I've uploaded a beta here [artboard-manager-1.6.0-beta.zip](https://github.com/bomberstudios/artboard-manager/files/2595617/artboard-manager-1.6.0-beta.zip) and it would be awesome if you could take it for a spin and send me your feedback before I merge the changes.

Thanks in advance for your time!
