### ISSUE TITLE
Sketch 52- doesn't work, no artboard arrangement

### ISSUE THREAD

**Issue by dlewand691** [bomberstudios/artboard-manager#24]
With the new update to Sketch 52, the plugin doesn't work. There's no error saying it's incompatible but none of the features work now. Please update!

**Comment by MYFW93** [comment]
Same for here. Waiting for update! :)

**Comment by bomberstudios** [comment]
Hi there. I've updated the code for the plugin with a new algorithm that (I think) works way better than the old one. I've uploaded a beta here [artboard-manager-1.6.0-beta.zip](https://github.com/bomberstudios/artboard-manager/files/2595617/artboard-manager-1.6.0-beta.zip) and it would be awesome if you could take it for a spin and send me your feedback before I merge the changes.

Thanks in advance for your time!
