### ISSUE TITLE
Artboards messing up

### ISSUE THREAD

**Issue by anfisign** [bomberstudios/artboard-manager#25]
For some reason, after the Sketch 52 update, the screens don't re-arrange so smoothly as before.
They're randomly meshing up.
I tried to rename all the artboards, but there seems to be no logic in the rearrangement.
See the gif below.

![2018-10-16 13 11 53](https://user-images.githubusercontent.com/22645943/47009468-411a6e80-d145-11e8-9c7d-79c626460ca6.gif)

**Comment by bomberstudios** [comment]
As stated in the README, the plugin is optimised for iPhone-sized artboards, and doesn't really work for other sizes. If you can share a copy of your document, I may take a look at it and see if I can make the situation better.

**Comment by bomberstudios** [comment]
Hi there. I've updated the code for the plugin with a new algorithm that (I think) works way better than the old one. I've uploaded a beta here [artboard-manager-1.6.0-beta.zip](https://github.com/bomberstudios/artboard-manager/files/2595617/artboard-manager-1.6.0-beta.zip) and it would be awesome if you could take it for a spin and send me your feedback before I merge the changes.

Thanks in advance for your time!
