### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by sigtm** [bomberstudios/artboard-manager#30]
Great plugin, I absolutely depend on it! Any chance dark mode support could be added, so the labels in the settings popup are readable in both modes?

![image](https://user-images.githubusercontent.com/18282258/48488469-1f360980-e821-11e8-9b90-ef00fd9d0091.png)

**Comment by bomberstudios** [comment]
This will take a while, but I'll upload a quick fix (always show a light background so you can at least read the labels : )

**Comment by bomberstudios** [comment]
The situation should be a bit better in v1.5.1 of the plugin

**Comment by sigtm** [comment]
Looks great! It's not important to me that it's dark to be honest, just that it's readable :) Although due to issue #29 I've had to disable it for the time being :(

**Comment by bomberstudios** [comment]
I hope the next version will make you happy, I see you're already using the beta : )

**Comment by bomberstudios** [comment]
Added Dark mode support in v2.1.0
