### ISSUE TITLE
Excluded artboards move to top

### ISSUE THREAD

**Issue by sogen** [bomberstudios/artboard-manager#40]
Excluded artboards change placement in the Layer List, moving to top (as if one executed the Bring to Front command on excluded artboards), instead of retaining their position in the Layer List. 
Any way to avoid this?

**Comment by bomberstudios** [comment]
Thanks for the report.

I'm trying to understand the issue, so if you could share a scenario in which this behaviour is a problem, that would really help me come up with a good solution.

**Comment by sogen** [comment]
np. 
it's 'cosmetic', just because it changed the layer organization in the layer list sidebar.
no biggie, closing!
