### ISSUE TITLE
Rearrangement of symboled Artboards not working

### ISSUE THREAD

**Issue by SeKiDeGe** [bomberstudios/artboard-manager#45]
Unfortunately, the plugin does not work for 1-2 weeks with Artboards, which have been converted into a symbol.

**Comment by philipp-lehmann** [comment]
Yupp, same for me
Sketch Version 60 (88103)

**Comment by bomberstudios** [comment]
Have you enabled the setting that controls that behavior (“Arrange Symbols”)?

**Comment by philipp-lehmann** [comment]
Hey, I had to remove and reinstall the latest version. Now it seems to work fine again. Thanks!
