### ISSUE TITLE
[Feature request] Toggle 

### ISSUE THREAD

**Issue by dgmaia** [bomberstudios/artboard-manager#51]
Hello

Would be possible to have an easy way to turn the plugin on and off?
Sometimes I just wanna move stuff around freely and later on 'run' the organiser.

At the moment I have been doing that enabling and disabling the plugin on Manage Plugins on Sketch.

**Comment by bomberstudios** [comment]
This was added in v2.1.0 (Plugins › Artboard Manager › Auto Mode), and uses `Ctrl Shift A` as the keyboard shortcut. Enabling Auto Mode will automatically arrange your Artboards.

Thanks for the request!

**Comment by dgmaia** [comment]
Thanks heeeeeaps!!
