### ISSUE TITLE
Sketch plugin file missing from download

### ISSUE THREAD

**Issue by ZillieZephyr** [bomberstudios/artboard-manager#6]
Howdy! The .sketchplugin file is missing from the folder.

**Comment by guerrero** [comment]
@ZillieZephyr have you tried to download it from [this link](https://github.com/bomberstudios/artboard-manager/releases/download/v1.3.1/artboard-manager.sketchplugin.zip)? It's placed on the release page

![download-link](https://user-images.githubusercontent.com/3751801/28590874-077e5b0e-7184-11e7-8e41-5fa62fc05bd8.png)
