### ISSUE TITLE
Make it work on symbols page?

### ISSUE THREAD

**Issue by thomasaull** [bomberstudios/artboard-manager#8]
Awesome plugin, really love it so far! It doesn't seem to do anything on the symbols page though (even with the command from the plugin menu) – would be awesome if you could make it work there aswell!

**Comment by vic-topcoder** [comment]
I like the [Symbol Organizer plugin](https://github.com/sonburn/symbol-organizer) which gives you more granular options on sorting elements based on names. I don't always want to automatically organize my symbols automatically while working, but think about a systematic approach towards systems. Maybe the plugin should take the `/` in the name patter into account as well. Still, I wouldn't think of adding the Organize Symbols pattern to the plugin yet.

**Comment by sigtm** [comment]
It would be a huge shame if there was a conflict between artboard manager and Symbol Organizer. I love artboard manager in general, and it's already saved me tons of time. On large projects my Symbols page really benefits from the more "heavy duty" Symbol Organizer plugin, though.

Maybe making it optional for symbols, or allowing it to be disabled for selected pages might be a solution?

**Comment by thomasaull** [comment]
Ah, I didn't know about Symbol Organizer at all. Great plugin and totally sufficient. So, I agree: No need to integrate this functionality into artboard manager :)
